const MONSTERS = [
    { 
        id: "slime_1", 
        name: "Wald-Schleim", 
        hp: 50, 
        maxHp: 50, 
        damage: 2, 
        attackSpeed: 2000,
        goldMin: 8, 
        goldMax: 12, 
        xp: 30, 
        icon: "🟢",
        level: 1,
        dropTable: []
    },
    { 
        id: "slime_2", 
        name: "Giftiger Schleim", 
        hp: 80, 
        maxHp: 80, 
        damage: 3, 
        attackSpeed: 2500,
        goldMin: 15, 
        goldMax: 25, 
        xp: 60, 
        icon: "💚",
        level: 3,
        dropTable: []
    },
    { 
        id: "crab_1", 
        name: "Fels-Krabbe", 
        hp: 120, 
        maxHp: 120, 
        damage: 5, 
        attackSpeed: 3000, 
        goldMin: 20, 
        goldMax: 35, 
        xp: 100, 
        icon: "🦀",
        level: 5,
        dropTable: []
    },
    { 
        id: "spider_1", 
        name: "Riesige Spinne", 
        hp: 150, 
        maxHp: 150, 
        damage: 7, 
        attackSpeed: 2200,
        goldMin: 30, 
        goldMax: 50, 
        xp: 150, 
        icon: "🕷️",
        level: 8,
        dropTable: []
    },
    { 
        id: "wolf_1", 
        name: "Grauer Wolf", 
        hp: 200, 
        maxHp: 200, 
        damage: 10, 
        attackSpeed: 2000,
        goldMin: 50, 
        goldMax: 80, 
        xp: 250, 
        icon: "🐺",
        level: 12,
        dropTable: []
    },
    { 
        id: "dragon_1", 
        name: "Drache des Waldes", 
        hp: 500, 
        maxHp: 500, 
        damage: 20, 
        attackSpeed: 3500,
        goldMin: 200, 
        goldMax: 350, 
        xp: 1000, 
        icon: "🐉",
        level: 20,
        dropTable: ["pick_4"]
    }
];