const MONSTERS = [
    { 
        id: "slime_1", 
        name: "Wald-Schleim", 
        hp: 50, 
        maxHp: 50, 
        damage: 2, 
        attackSpeed: 2000,
        goldMin: 8, 
        goldMax: 12, 
        xp: 30, 
        icon: "🟢",
        level: 1,
        dropTable: []
    },
    { 
        id: "slime_2", 
        name: "Giftiger Schleim", 
        hp: 80, 
        maxHp: 80, 
        damage: 3, 
        attackSpeed: 2500,
        goldMin: 15, 
        goldMax: 25, 
        xp: 60, 
        icon: "💚",
        level: 3,
        dropTable: []
    },
    { 
        id: "crab_1", 
        name: "Steinkrabbe", 
        hp: 70, 
        maxHp: 70, 
        damage: 3, 
        attackSpeed: 2400, 
        goldMin: 10, 
        goldMax: 18, 
        xp: 45, 
        icon: "🦀",
        sprite: "Media/Images/Monster/Stone_Crab_A.png",
        level: 1,
        tags: ["coast"],
        dropTable: []
    },
    { 
        id: "captain_1", 
        name: "Ertrunkener Kapitän", 
        hp: 105, 
        maxHp: 105, 
        damage: 5, 
        attackSpeed: 2600, 
        goldMin: 16, 
        goldMax: 28, 
        xp: 78, 
        icon: "☠️",
        sprite: "Media/Images/Monster/Drunken_Captain.png",
        level: 3,
        tags: ["coast"],
        dropTable: []
    },
    { 
        id: "thief_1", 
        name: "Wegelagerer", 
        hp: 92, 
        maxHp: 92, 
        damage: 6, 
        attackSpeed: 1850, 
        goldMin: 18, 
        goldMax: 34, 
        xp: 92, 
        icon: "🗡️",
        sprite: "Media/Images/Monster/Thief_B.png",
        level: 4,
        tags: ["coast"],
        dropTable: []
    },
    { 
        id: "spider_1", 
        name: "Riesige Spinne", 
        hp: 150, 
        maxHp: 150, 
        damage: 7, 
        attackSpeed: 2200,
        goldMin: 30, 
        goldMax: 50, 
        xp: 150, 
        icon: "🕷️",
        level: 8,
        dropTable: []
    },
    { 
        id: "wolf_1", 
        name: "Grauer Wolf", 
        hp: 200, 
        maxHp: 200, 
        damage: 10, 
        attackSpeed: 2000,
        goldMin: 50, 
        goldMax: 80, 
        xp: 250, 
        icon: "🐺",
        level: 12,
        dropTable: []
    },
    { 
        id: "dragon_1", 
        name: "Drache des Waldes", 
        hp: 500, 
        maxHp: 500, 
        damage: 20, 
        attackSpeed: 3500,
        goldMin: 200, 
        goldMax: 350, 
        xp: 1000, 
        icon: "🐉",
        level: 20,
        dropTable: ["pick_4"]
    }
];
